import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { getFilesFromDataDir, generateRoutes } from "../utils";
// import { Navigation } from "../components/Navigation";

// const files = async () => {
//   const content = await getFilesFromDataDir();
//   console.log(content)
//   return content;
// };

// const paths = generateRoutes(files);

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to News!</h1>
        {/* {paths && paths.map((path) => {
          return <Navigation path={path} key={path.params.news} />
        })} */}
      </main>
    </div>
  );
};

export default Home;
