import type { NextPage } from "next";
import { GetStaticProps } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { getFilesFromDataDir, generateRoutes } from "../utils";
import { Navigation } from "../components/Navigation";

import { PathsEntity } from "../types";

const Home: NextPage = ({paths}: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to News!</h1>
        {
          // @ts-ignore
          paths.map((params: PathsEntity, index: number) => {
            // @ts-ignore
            return <Navigation params={params} key={index} />;
          })
        }
      </main>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const files = (await getFilesFromDataDir()) as string[];
  const paths = generateRoutes(files);

  return {
    props: { paths },
    revalidate: 1,
  };
};

export default Home;
