---
name: Build and Deploy
on:
  schedule:
    - cron: "50 7 * * *"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install and Build
        uses: actions/setup-node@v1
        with:
          node-version: "14.15.4"

      - run: npm install

      - run: npm run build-static
        env:
          CI: true
          DEPLOY_TARGET: gh-pages

      - run: touch frontend/out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
          FOLDER: frontend/out
          CLEAN: true
