---
name: Publish static website
on:
  schedule:
    - cron: "00 8 * * *"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_GH_ACTIONS_BOT_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]sx?') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-


      - name: Install and Build
        uses: actions/setup-node@v1
        with:
          node-version: "14.15.4"

      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-


      - name: Build static pages
        run: cd frontend && npm install && npm run build-static
        env:
          CI: true
          DEPLOY_TARGET: gh-pages
          NEXT_TELEMETRY_DISABLED: 1

      - name: No jekyll
        run: touch frontend/out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: frontend/out
          CLEAN: true

      - run: echo news_slug=$(date +"%Y-%m-%d") >> $GITHUB_ENV

      - id: send-slack-message
        name: Inform news channel on slack
        uses: GoldenspearLLC/slack-chat-postmessage@v3
        with:
          channel: "#news"
          text: "News published for today. Check it out here https://pavanprakash21.github.io/news/${{ env.news_slug }}"
